version: '3.8'

services:
  db:
    image: postgres:15
    container_name: cards-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cardsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./prisma/partitioned_card_setup.sql:/docker-entrypoint-initdb.d/partitioned_card_setup.sql:ro

  backend:
    build: .
    container_name: cardnexus-backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/cardsdb
    volumes:
      - .:/app
    command: npm run start

volumes:
  pgdata: